# Generated by Django 4.0.3 on 2022-08-09 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seoulbike', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='voter',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
